name: Maven CI

# Triggers manually or on push or pull request on the main branch
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Runs the Maven test phase on the project
  maven_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

    # Cache the build files
    - name: Cache build
      uses: actions/cache@v3
      with:
        key: build-${{hashFiles('pom.xml')}}
        path: .

    # Run Maven tests
    - name: Test with Maven
      run: mvn test

    # Upload Jacoco coverage results as artifact
    - name: Upload jacoco results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Jacoco coverage results
        path: target/site/jacoco

  # Uploads dependency graph to GitHub to receive Dependabot alerts 
  update_dependence_graph:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    # Restore cached build files from the previous job
    - name: Restore cached build
      uses: actions/cache@v3
      with:
        key: build-${{hashFiles('pom.xml')}}
        path: .

    # Update the Maven dependency graph
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
